### ISSUE TITLE
API can't call node exit for schain with multisig owner

### ISSUE THREAD

**Issue by OleksanderSalamatov** [skalenetwork/skale-manager#800] opened 2022-04-07 16:43 UTC
When we call node exit on node where is a schain with multisig owner, skale-api can't send transaction because of "execution reverted: The schain does not exist" error. nodeExit on schains owned by PK is called without errors

Steps:
1) call init exit on node with schain owned by multisig
2) call skale exit start on same node
3) monitor api logs

```
[2022-04-07 14:18:53,659] 11 INFO /api/v1/health/schains docker_utils: Initing docker client with host unix:///var/run/skale/docker.sock
[2022-04-07 14:18:53,660] 11 INFO /api/v1/health/schains app: Processing request b33eda102a
[2022-04-07 14:18:53,660] 11 INFO /api/v1/health/schains skale_base: Initing skale.py, endpoint: 6d35dc511bd8ffc1b039bc407786d8c84d226898818f13a1ab076f9f7bdb4da4 wallet: RedisWalletAdapter
[2022-04-07 14:18:53,688] 11 INFO /api/v1/health/schains skale_manager: Debug contracts found in ABI file
[2022-04-07 14:18:53,743] 11 ERROR None tools: Dry run for method failed with error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/skale/transactions/tools.py", line 60, in make_dry_run_call
    estimated_gas = estimate_gas(skale.web3, method, opts)
  File "/usr/local/lib/python3.8/site-packages/skale/transactions/tools.py", line 75, in estimate_gas
    estimated_gas = method.estimateGas(
  File "/usr/local/lib/python3.8/site-packages/web3/contract.py", line 1039, in estimateGas
    return estimate_gas_for_function(
  File "/usr/local/lib/python3.8/site-packages/web3/contract.py", line 1620, in estimate_gas_for_function
    return web3.eth.estimate_gas(estimate_transaction, block_identifier)
  File "/usr/local/lib/python3.8/site-packages/web3/eth.py", line 759, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "/usr/local/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/local/lib/python3.8/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/usr/local/lib/python3.8/site-packages/web3/manager.py", line 170, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/usr/local/lib/python3.8/site-packages/web3/manager.py", line 70, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/usr/local/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 576, in raise_solidity_error_on_revert
    raise ContractLogicError(response['error']['message'])
web3.exceptions.ContractLogicError: execution reverted: The schain does not exist
[2022-04-07 14:18:53,936] 10 INFO /api/v1/health/sgx utils: Response received: {'id': 0, 'jsonrpc': '2.0', 'result': {'errorMessage': '', 'status': 0, 'version': '1.83.0'}}
[2022-04-07 14:18:53,936] 10 INFO /api/v1/health/sgx app: Request finished 096cab5776, time elapsed: 1s
[2022-04-07 14:18:53 +0000] [10] [DEBUG] GET /api/v1/node/hardware
[2022-04-07 14:18:53,938] 10 INFO /api/v1/node/hardware helper: Checking if skale-admin inited ...
[2022-04-07 14:18:53,938] 10 INFO /api/v1/node/hardware filelock: Lock 140075795753424 acquired on /skale_node_data/init.lock
[2022-04-07 14:18:53,938] 10 INFO /api/v1/node/hardware helper: Skale admin inited
[2022-04-07 14:18:53,938] 10 INFO /api/v1/node/hardware filelock: Lock 140075795753424 released on /skale_node_data/init.lock
[2022-04-07 14:18:53,939] 10 INFO /api/v1/node/hardware utils: Send request: {'id': 0, 'jsonrpc': '2.0', 'method': 'getPublicECDSAKey', 'params': {'keyName': 'ee8502226235f86b56ccb38aa75796e805f249f27dc38c90eca7eeb8a78e968c'}}
[2022-04-07 14:18:54,079] 11 ERROR None custom_thread: Error was occurred during the execution. Function: exit. Error execution reverted: The schain does not exist.
Traceback (most recent call last):
  File "/usr/src/admin/tools/custom_thread.py", line 57, in safe_run_func
    self.func(self.opts)
  File "/usr/src/admin/core/node.py", line 185, in exit
    self.skale.manager.node_exit(self.config.id, wait_for=True)
  File "/usr/local/lib/python3.8/site-packages/skale/contracts/base_contract.py", line 113, in wrapper
    tx_res.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/skale/transactions/result.py", line 91, in raise_for_status
    raise RevertError(self.dry_run_result['error'])
skale.transactions.exceptions.RevertError: execution reverted: The schain does not exist
[2022-04-07 14:18:54,391] 10 INFO /api/v1/node/hardware utils: Response received: {'id': 0, 'jsonrpc': '2.0', 'result': {'PublicKey': 'f8c3e17591f3cd8a797a6f50d6d1e44c9270624498af944c4f...', 'errorMessage': '', 'publicKey': 'f8c3e17591f3cd8a797a6f50d6d1e44c9270624498af944c4f...', 'status': 0}}
```

**Comment by dmytrotkk** [comment] 2022-04-08 17:33
Executed transaction without dry run on a node and it failed: https://rinkeby.etherscan.io/tx/0x015bc8255b33cb686324676658376ac52dbc964054b36c36fffa991d9dda06d5

@payvint or @DimaStebaev should take a look now

**Comment by gannakulikova** [comment] 2022-04-11 10:53
Not critical for V2 release, assigned to V2.1

**Comment by DimaStebaev** [comment] 2022-04-13 06:44
It needs further investigation.
I think it's caused by an error during SKALE chain termination. Because chains are not removed form mainnet I think it's not affected.
This should be fixed before we delete first SKALE chain from mainnet.

**Comment by gannakulikova** [comment] 2022-07-14 10:50
Completed

**Closed as completed by gannakulikova** 2022-07-14 10:50 UTC
Labels: bug
